from __future__ import annotations

# Prefixes for param groups. When Settings.use_prefixes is True, any query
# param whose lowercased name starts with one of these is stripped even if
# it isn't listed explicitly in DEFAULT_PATTERNS.
_PREFIXES: tuple[str, ...] = (
    "utm_",
    "mtm_",
    "pk_",
    "hsa_",
    "af_",
    "adj_",
    "at_",
    "cm_",
    "bsft_",
    "mt_",
    "fb_",
    "hs_",
    "piwik_",
    "mc_",
    "ir_",
    "vgo_",
    "sms_",
    "eml_",
    "nb_",
)

PREFIXES: tuple[str, ...] = _PREFIXES

DEFAULT_PATTERNS: frozenset[str] = frozenset({
    # ── UTM ──────────────────────────────────────────────────────────────
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_term",
    "utm_content",
    "utm_id",
    "utm_cid",
    "utm_reader",
    "utm_viz",
    "utm_pubreferrer",
    "utm_nooverride",
    "utm_source_platform",
    "utm_creative_format",
    "utm_marketing_tactic",
    "utm_compaign",
    "utm_prid",
    "utm_wave",
    "utm_lob",
    "utm_emailid",
    "utm_email",
    "utm_newsletterid",
    "utm_tag",
    "utm_adset",
    "utm_adgroup",
    "utm_ad",
    "utm_affiliate",
    "utm_brand",
    "utm_campaignid",
    "utm_campaign_name",
    "utm_channel",
    "utm_creative",
    "utm_emcid",
    "utm_emmid",
    "utm_id_",
    "utm_internal",
    "utm_journey_id",
    "utm_keyword",
    "utm_klaviyo_id",
    "utm_name",
    "utm_place",
    "utm_product",
    "utm_referrer",
    "utm_roistat",
    "utm_serial",
    "utm_session",
    "utm_siteid",
    "utm_social",
    "utm_social-type",
    "utm_source_code",
    "utm_supplier",
    "utm_swu",
    "utm_umguk",
    "utm_userid",
    "utm_viz_id",

    # ── Google Ads / Analytics ────────────────────────────────────────────
    "gclid",
    "gclsrc",
    "dclid",
    "gbraid",
    "wbraid",
    "gad_source",
    "gad_campaignid",
    "usqp",
    "sscp",
    "_ga",
    "_gl",

    # ── Social click IDs ─────────────────────────────────────────────────
    "fbclid",
    "igshid",
    "ttclid",
    "twclid",
    "tgclid",
    "ssp_iabi",
    "ssp_iaba",
    "fbadid",
    "nb_placement",
    "nb_expid_meta",
    "li_fat_id",
    "sccid",
    "qclid",

    # ── Spotify ──────────────────────────────────────────────────────────
    "si",
    "nd",
    "dl_branch",
    "context",

    # ── HubSpot ──────────────────────────────────────────────────────────
    "_hsenc",
    "_hsmi",
    "__hsfp",
    "__hssc",
    "__hstc",
    "hsCtaTracking",
    "hsa_acc",
    "hsa_ad",
    "hsa_cam",
    "hsa_grp",
    "hsa_kw",
    "hsa_la",
    "hsa_mt",
    "hsa_net",
    "hsa_ol",
    "hsa_src",
    "hsa_tgt",
    "hsa_ver",

    # ── Matomo / Piwik ───────────────────────────────────────────────────
    "mtm_campaign",
    "mtm_cid",
    "mtm_content",
    "mtm_group",
    "mtm_keyword",
    "mtm_medium",
    "mtm_placement",
    "mtm_source",
    "pk_campaign",
    "pk_medium",
    "pk_source",
    "pk_keyword",
    "pk_cid",
    "pk_content",

    # ── Analytics ────────────────────────────────────────────────────────
    "_ke",
    "_sgm_campaign",
    "_sgm_source",
    "_sgm_action",
    "_sgm_term",
    "_sgm_pinned",
    "_bhlid",
    "_bdadid",
    "_clde",
    "_cldee",
    "_ope",
    "_io_session_id",
    "__io_lv",
    "__s",
    "_zucks_suid",
    "pk_vid",

    # ── Email marketing ──────────────────────────────────────────────────
    "mc_cid",
    "mc_eid",
    "bsft_clkid",
    "bsft_eid",
    "bsft_mid",
    "bsft_uid",
    "bsft_aaid",
    "bsft_ek",
    "mkt_tok",
    "vgo_ee",
    "ml_subscriber",
    "ml_subscriber_hash",
    "mindbox-message-key",
    "ems_dl",
    "emcs_t",

    # ── Affiliate / Ad networks ──────────────────────────────────────────
    "cjdata",
    "cjevent",
    "ir_campaignid",
    "ir_adid",
    "ir_partnerid",
    "irclickid",
    "sscid",
    "awc",
    "admitad_uid",
    "btag",
    "afc",
    "ranMID",
    "ranEAID",
    "ranSiteID",
    "ftag",
    "janet",
    "bance_xuid",
    "adsterra_clid",
    "adsterra_placement_id",
    "loclid",
    "ldtag_cl",
    "lt_r",
    "srclt",
    "ucid",
    "bta_tid",
    "bta_c",

    # ── Adjust ───────────────────────────────────────────────────────────
    "adj_t",
    "adj_label",
    "adj_campaign",
    "adj_creative",
    "gps_adid",
    "unicorn_click_id",
    "adjust_creative",
    "adjust_tracker_limit",
    "adjust_tracker",
    "adjust_adgroup",
    "adjust_campaign",
    "adjust_referrer",
    "external_click_id",

    # ── AppsFlyer ────────────────────────────────────────────────────────
    "af_xp",
    "af_ad",
    "af_adset",
    "af_click_lookback",
    "af_force_deeplink",
    "is_retargeting",
    "pid",

    # ── Branch.io ────────────────────────────────────────────────────────
    "_branch_match_id",
    "_branch_referrer",

    # ── Coremetrics ──────────────────────────────────────────────────────
    "cm_me",
    "cm_cr",
    "cm_mmc",

    # ── AT Internet ──────────────────────────────────────────────────────
    "at_custom",
    "at_campaign",
    "at_campaign_type",
    "at_creation",
    "at_emailtype",
    "at_link",
    "at_link_id",
    "at_link_origin",
    "at_link_type",
    "at_medium",
    "at_ptr_name",
    "at_recipient_id",
    "at_recipient_list",
    "at_send_date",

    # ── Adobe / Marketo ──────────────────────────────────────────────────
    "s_cid",
    "adobe_mc_ref",
    "adobe_mc_sdid",
    "iesrc",
    "mailId",

    # ── Yandex ───────────────────────────────────────────────────────────
    "yclid",
    "ysclid",
    "clckid",
    "ym_tracking_id",
    "aiad_clid",

    # ── MyTracker ────────────────────────────────────────────────────────
    "mt_click_id",
    "mt_network",
    "mt_campaign",
    "mt_adset",
    "mt_creative",
    "mt_medium",
    "mt_sub1",
    "mt_sub2",
    "mt_sub3",
    "mt_sub4",
    "mt_sub5",

    # ── Microsoft (Bing) ─────────────────────────────────────────────────
    "msclkid",
    "oicd",
    "cvid",

    # ── Facebook / Meta ──────────────────────────────────────────────────
    "fb_action_ids",
    "fb_action_types",
    "fb_comment_id",
    "fb_ref",
    "fb_source",

    # ── Pinterest ────────────────────────────────────────────────────────
    "epik",
    "campaign_id",
    "ad_group_id",
    "pin_promotion_id",
    "pin_id",

    # ── Link shorteners / SMS ────────────────────────────────────────────
    "sms_click",
    "sms_source",
    "sms_uph",

    # ── Redirect / session ───────────────────────────────────────────────
    "redirect_to",
    "return_to",
    "next",
    "continue",
    "session_id",
    "sid",
    "phpsessid",
    "jsessionid",
    "view_id",
    "visit_id",

    # ── Cache busters ────────────────────────────────────────────────────
    "_",
    "cb",
    "cache",
    "nocache",
    "rand",
    "random",
    "r",
    "ts",
    "_t",
    "timestamp",

    # ── Misc / platform-specific ─────────────────────────────────────────
    "_openstat",
    "oft_id",
    "wt_mc",
    "hootpostid",
    "wprov",
    "ref",
    "source",
    "origin",
    "sns",
    "social",
    "email",
    "recipient",
    "newsletter",
    "mbid",
    "trk",
    "trk_contact",
    "trk_msg",
    "trk_module",
    "trk_sid",
    "vero_conv",
    "vero_id",
    "x-clickref",
    "x-source",
    "x-a-medium",
    "link_source",
    "taid",
    "erid",
    "tduid",
    "vc_lpp",
    "int_content",
    "int_term",
    "int_source",
    "int_medium",
    "int_campaign",
    "itm_source",
    "itm_medium",
    "itm_campaign",
    "itm_content",
    "itm_term",
    "oprtrack",
    "xtor",
    "wickedid",
    "icid",
    "rb_clickid",
    "dm_i",
    "sb_referer_host",
    "mkwid",
    "pcrid",
    "ef_id",
    "s_kwcid",
    "guccounter",
    "guce_referrer",
    "guce_referrer_sig",
    "action_object_map",
    "action_ref_map",
    "action_type_map",
    "bemobdata",
    "cstrackid",
    "jmtyClId",
    "Tcsack",
    "mindbox-click-id",
    "uzcid",
    "beyond_uzcvid",
    "beyond_uzmcvid",
    "gci",
    "elqTrackId",
    "elq",
    "elqaid",
    "elqat",
    "elqCampaignId",
    "elqak",
    "oex",
    "oly_anon_id",
    "oly_enc_id",
    "otc",
    "visitor_id",
    "pi_opt_in",
    "piCId",
})
